config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :likes, only: [:create]
      resources :comments, only: [:new, :create, :destroy]
    end
  end

    #API routes
    namespace :api do
      resources :users, only: [:show] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
end

app/views/partials/_comment.html.erb
<p><%= comment.author.name %>: <%= comment.text%></p>

app/views/partials/_delete_button.html.erb
<% if can? :destroy, model%>
  <%= button_to "Delete", url, method: :delete,  class: 'delete-btn'%>
<%end %>

app/views/partials/_form.html.erb
<%= form_with model:([@post, @comments]), html: { class: 'form-c'} do |form|%>
<%=form.label "Enter Comment", class: 'field-label-c'%>
<%=form.text_area :text, class: 'field-c'%>
<%=form.submit "Comment", class: 'form-btn'%>
<%end%>

app/views/partials/_post.html.erb
<%=link_to user_post_path(@user, post) do %>
  <div class="post">
    <h3><%= post.title %></h3>
    <p><%= post.text %></p>
    <p class='post-total'>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %> </p>
  </div>
<% end %>

<% if can? :destroy, post %>
  <%= form_for [@user, post], url: user_post_path(@user, post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } do |f| %>
    <%= f.submit "Delete Post", :class => 'delete_btn' %>
  <% end %>
<% end %>

app/views/partials/_user.html.erb
<div class='user-content'>
  <% if user.photo.present? %>
    <%= image_tag user.photo, alt: "#{user.name} profile image", class: 'profile' %>
  <% else %>
    <!-- Add a placeholder image or any default image -->
    <%= image_tag '312-3120300_default-profile-hd-png-download.png', alt: 'Default profile image', class: 'profile' %>
  <% end %>
  <div class='user-content2'>
    <%= link_to user, class: 'user-content-details' do %>
    <div class='user-info'>
    <h2><%= user.name %></h2>
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>
    <p class='user-post-total'>Number of posts: <%=user.posts_counter%> </p>
    <%end%>
  </div>
 </div>