config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :likes, only: [:create]
      resources :comments, only: [:new, :create, :destroy]
    end
  end

    #API routes
    namespace :api do
      resources :users, only: [:show] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  after_save :update_posts_counter
  after_destroy :reduce_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  after_initialize :set_defaults

  def return_five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def reduce_posts_counter
    author.decrement!(:posts_counter)
  end

  def set_defaults
    self.likes_counter ||= 0
    self.comments_counter ||= 0
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  # skip_before_action :verify_authenticity_token
  # skip_before_action :authenticate_user!
  # respond_to :json
  # load_and_authorize_resource except: %i[index show]

  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(comments: [:author]).where(author_id: params[:user_id])
    if @posts
      render json: @posts.to_json, status: :ok
    else
      render json: { status: 'Error', errors: @posts.errors }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource except: %i[index show]

  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(comments: [:author]).where(author_id: params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:errors] = 'Invalid post!'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = @post.author

    Comment.where(post_id: @post.id).destroy_all # Delete associated comments

    if @post.destroy
      redirect_to user_posts_path(@user), notice: 'Post was successfully deleted'
    else
      flash.now[:alert] = 'Failed to delete post.'
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
div class='header'>
  <h1>Blog App</h1>
  <div class='button-cont'>
	  <%= button_to("Home", root_path, method: :get, class: 'log-out') %>
	  <%= button_to("Log Out", destroy_user_session_path, method: :delete, class: 'log-out') %>
  </div>
</div>

<%= render 'partials/user', user: @user %>
<main class="post-index">
  <% @posts.reverse_each do |post| %>
    <div class="post-details">
      <%= render 'partials/post', post: post %>

      <div>
        <%= link_to "Add Comment", new_user_post_comment_path(@user, post), class: 'add_comment' %>
        <%= form_with url: user_post_likes_path(post.author.id, post.id) do |form| %>
          <%= form.submit 'Like', class: 'like_btn' %>
        <% end %>
      </div>

      <div class="comment-container">
      <h3>Comments</h3>
        <% post.return_five_most_recent_comments.reverse_each do |comment| %>
          <%= render 'partials/comment', comment: comment %>
        <% if can? :destroy, comment %>
          <%= form_for [@user, post, comment], url: user_post_comment_path(post.author, post, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } do |f| %>
            <%= f.submit "Delete Comment" %>
          <% end %>
        <% end %>
        <% end %>
      </div>

    </div>
  <% end %>
  <div class='pagination'>Pagination</div>
</main>

app/views/posts/new.html.erb
<div class='header'>
  <h1>Blog App</h1>
  <div class='button-cont'>
	  <%= button_to("Home", root_path, method: :get, class: 'log-out') %>
	  <%= button_to("Log Out", destroy_user_session_path, method: :delete, class: 'log-out') %>
  </div>
</div>

<div>
  <%= form_with model: @post, class:'form', url: user_posts_path(@user) do |form| %>
    <%= form.label :title, class: 'post_label' %>
    <%= form.text_field :title, autofocus: true, required: true, class:'post_title' %>
    <%= form.label :text, class: 'post_label' %>
    <%= form.text_area :text, autofocus: true, required: true, class:'post_text' %>
    <%= form.submit "Post", class: 'post_btn' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class='header'>
  <h1>Blog App</h1>
  <div class='button-cont'>
    <%= button_to("Home", root_path, method: :get, class: 'log-out') %>
    <%= button_to("Log Out", destroy_user_session_path, method: :delete, class: 'log-out') %>
  </div>
</div>

<main class='user-cont2'>
  <div class="post-in-show">
    <div class="post-in-show2">
      <h3><%= @post.title %> by <%= @post.author.name %></h3>
      <p>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
    </div>
    <p><%= @post.text %></p>
  </div>
  <div class="comment-container">
    <h3>Comments</h3>
    <% @post.comments.each do |comment| %>
      <%= render 'partials/comment', comment: comment %>
      <% if can? :destroy, comment %>
        <%= form_for [@user, @post, comment], url: user_post_comment_path(@post.author, @post, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } do |f| %>
          <%= f.submit "Delete Comment" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</main>